name: Archive Branch

on:
  push:
    branches:
      - main

jobs:
  create_archive_pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check if curl is installed
        run: type -p curl >/dev/null || (sudo apt update && sudo apt install curl -y)

      - name: Install GitHub CLI
        run: |
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg \
          && sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg \
          && echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
          && sudo apt update \
          && sudo apt install gh -y

      - name: Create Archive PR
        run: |
          gh auth login
          gh pr create --base archive --head main --title "Archive PR" --body "This is an archive PR created automatically after merging to main branch."
        env: 
          GH_TOKEN: ${{ secrets.ACCESS_TOKEN }}
