name: Archive Branch

on:
  push:
    branches:
      - main

jobs:
  create_archive_pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login
        run: |
          gh auth login
        env: 
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      - name: Set Archive HEAD
        run: |
          gh repo set-default adachi-team/docs
      - name: Create Archive PR
        run: |
          gh pr create --base archive --head main --title "Archive PR" --body "This is an archive PR created automatically after merging to main branch."
