name: automerge
on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
  pull_request_review:
    types:
      - submitted
  check_suite:
    types:
      - completed
  status: {}
jobs:
  check-contributor:
    runs-on: ubuntu-latest
    
    steps:
      - name: Get PR number
        id: pr-number
        run: echo "::set-output name=pr-number::${{ github.event.pull_request.number }}"
      
      - name: Get PR details
        id: pr-details
        run: |
          echo "::set-output name=contributor::$(curl -s -X GET \
          -H \"Accept: application/vnd.github.v3+json\" \
          https://api.github.com/repos/${{ github.repository }}/pulls/${{ steps.pr-number.outputs.pr-number }}/ \
          | jq -r '.head.user.login')"
      
      - name: Check contributor
        run: |
          contributor="${{ steps.pr-details.outputs.contributor }}"
          if [ "$contributor" != "H-Unamed" ]; then
            echo "Contributor is not H-Unamed"
            exit 1
          fi
          
          echo "Contributor is H-Unamed, continue with other steps"
