name: automerge
on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
  pull_request_review:
    types:
      - submitted
  check_suite:
    types:
      - completed
  status: {}
jobs:
  check-contributor:
    runs-on: ubuntu-latest
    
    steps:      
      - name: Get PR details
        id: pr-details
        run: |
          echo "contributor=$(curl -s -X GET \
          -H \"Accept: application/vnd.github.v3+json\" \
          https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/ \
          | jq -r '.head.user.login')" >> $CONTRIBUTOR
          echo ${{ github.repository }}
          echo ${{ github.event.pull_request.number }}
          echo "$CONTRIBUTOR"
      
      - name: Check contributor
        run: |
          contributor="$CONTRIBUTOR"
          if [ "$contributor" != "H-Unamed" ]; then
            echo "Contributor is not H-Unamed"
            exit 1
          fi
          
          echo "Contributor is H-Unamed, continue with other steps"
